# Generated by Django 3.1.7 on 2021-05-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrupar_alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='caracteristica_aluno',
            field=models.CharField(max_length=200, verbose_name='Característica Aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_aluno',
            field=models.CharField(max_length=200, verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='caracteristica_grupo',
            field=models.CharField(max_length=200, verbose_name='Característica Grupo'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='limite_integrante_grupo',
            field=models.IntegerField(verbose_name='Limite de Integrantes'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nome_grupo',
            field=models.CharField(max_length=200, verbose_name='Grupo'),
        ),
    ]
